# Generated by Django 3.0.7 on 2020-07-28 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_api', '0005_auto_20200726_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('i', 'In-Cart'), ('o', 'Ordered'), ('d', 'Delivered'), ('c', 'Cancelled')], default='i', max_length=1)),
                ('product_title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('qty', models.BooleanField()),
                ('total_price', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('associated_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_api.Product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
