# Generated by Django 3.0.7 on 2020-07-28 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_api', '0002_auto_20200728_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='display_id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('i', 'In-Cart'), ('w', 'Wishlisted'), ('o', 'Ordered'), ('d', 'Delivered'), ('c', 'Cancelled')], default='i', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('p', 'Placed'), ('a', 'Acknowledged'), ('r', 'Ready'), ('t', 'In Transit'), ('e', 'Returned'), ('l', 'Partially Returned'), ('d', 'Dismissed')], default='p', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updater', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
