# Generated by Django 3.0.7 on 2020-07-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0003_auto_20200728_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='linked_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_api.Order'),
        ),
    ]
