# Generated by Django 3.0.7 on 2020-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0005_auto_20200729_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='display_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
