# Generated by Django 3.0.7 on 2020-07-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_auto_20200725_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
