# Generated by Django 3.0.7 on 2020-07-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_auto_20200725_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
